name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    name: Linting and Complexity Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Gather Python changed files
        id: changed-py-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            ww3/**/*.py
            bin/**/*.py

      - name: Lint with ruff
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: |
          pip install ruff
          ruff format --check ${{ steps.changed-py-files.outputs.all_changed_files }}
          ruff check ${{ steps.changed-py-files.outputs.all_changed_files }} --select I

      - name: Run Sourcery Complexity Analysis
        working-directory: .
        run: 
          pip install sourcery-analytics
          sourcery-analytics assess .

  tests:
    name: Unit Tests
    env:
      PYTHONPATH: '.'
    runs-on: ubuntu-22.04
    container:
      image: pytorch/pytorch:2.10.0-cuda12.6-cudnn9-devel

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install . pyright pytest pytest-cov --break-system-packages

    - name: Install git  # necessary for the tj-action/changed-py-files
      run: apt-get update && apt-get install -y git

    - name: Gather Python changed files
      id: changed-py-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          *.py
          **/*.py

    - name: Test with pytest
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        pytest tests/
